"""
protocols/ua.py - Understand-Anything protocol handler.

Adapted from the original call_of_core/mp-watcher.py. Reads a local
knowledge-graph.json (generated by the separate Understand-Anything tool)
and answers structural queries about a codebase from it. No network calls.
"""

import json
import os

TAG = "ua"

UA_SEARCH_DIRS = [
    os.getcwd(),
    r"C:\git",
    r"C:\m",
    os.path.join(os.path.expanduser("~"), "Desktop"),
]


def _find_graph(path_hint=None):
    candidates = []
    if path_hint:
        p = os.path.expanduser(path_hint)
        if os.path.isfile(p):
            candidates.append(p)
        else:
            candidates.append(os.path.join(p, ".understand-anything", "knowledge-graph.json"))
    for d in UA_SEARCH_DIRS:
        candidates.append(os.path.join(d, ".understand-anything", "knowledge-graph.json"))
    for c in candidates:
        if os.path.isfile(c):
            return c
    return None


def _load(path_hint=None):
    p = _find_graph(path_hint)
    if not p:
        raise FileNotFoundError("No knowledge-graph.json found. Run /understand first.")
    with open(p, encoding="utf-8") as f:
        return json.load(f), p


def _score(node, query):
    q_words = query.lower().split()
    text = " ".join([
        node.get("name", ""), node.get("summary", ""), node.get("filePath", ""),
        node.get("id", ""), " ".join(node.get("tags", [])),
    ]).lower()
    return sum(1 for w in q_words if w in text)


def dispatch(cmd):
    action = cmd.get("action", "").lower().strip()
    path_hint = cmd.get("path")
    count = int(cmd.get("count", 10))

    try:
        graph, graph_path = _load(path_hint)
    except FileNotFoundError as e:
        return f"[UA ERROR] {e}"
    except Exception as e:
        return f"[UA ERROR] Failed to load graph: {e}"

    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])
    layers = graph.get("layers", [])
    tour = graph.get("tour", [])
    proj = graph.get("project", {})

    if action == "ua_info":
        type_counts = {}
        for n in nodes:
            t = n.get("type", "?")
            type_counts[t] = type_counts.get(t, 0) + 1
        lines = [
            f"[UA INFO] {graph_path}",
            f"  Project : {proj.get('name','?')}",
            f"  Langs   : {', '.join(proj.get('languages', []))}",
            f"  Nodes   : {len(nodes)}  Edges: {len(edges)}  Layers: {len(layers)}  Tour: {len(tour)} steps",
            "  Node types: " + ", ".join(f"{t}:{c}" for t, c in sorted(type_counts.items(), key=lambda x: -x[1])),
        ]
        return "\n".join(lines)

    elif action == "ua_search":
        query = cmd.get("query", "").strip()
        if not query:
            return "[UA ERROR] ua_search requires a 'query' field"
        scored = sorted([(n, _score(n, query)) for n in nodes], key=lambda x: -x[1])
        top = [(n, s) for n, s in scored if s > 0][:count]
        if not top:
            return f"[UA SEARCH] No matches for '{query}'"
        lines = [f"[UA SEARCH] '{query}' - showing {len(top)}"]
        for n, _ in top:
            lines.append(f"\n  [{n.get('type','?')}] {n.get('name','?')}  id={n.get('id','?')}")
            if n.get("filePath"):
                lines.append(f"    file: {n['filePath']}")
            if n.get("summary"):
                lines.append(f"    summary: {n['summary'][:80]}")
        return "\n".join(lines)

    elif action == "ua_node":
        node_id = cmd.get("id", "").strip()
        node = next((n for n in nodes if n.get("id") == node_id), None) or \
               next((n for n in nodes if node_id.lower() in n.get("id", "").lower()), None)
        if not node:
            return f"[UA ERROR] Node '{node_id}' not found"
        nid = node["id"]
        out_e = [e for e in edges if e.get("source") == nid]
        in_e = [e for e in edges if e.get("target") == nid]
        lines = [
            f"[UA NODE] {node.get('name','?')}  ({node.get('type','?')})",
            f"  file: {node.get('filePath','')}",
            f"  summary: {node.get('summary','')}",
        ]
        if out_e:
            lines.append("  -> outgoing: " + ", ".join(f"{e.get('type')}->{e.get('target')}" for e in out_e[:6]))
        if in_e:
            lines.append("  <- incoming: " + ", ".join(f"{e.get('source')}->{e.get('type')}" for e in in_e[:6]))
        return "\n".join(lines)

    elif action == "ua_layer":
        name_q = cmd.get("name", "").lower().strip()
        layer = next((l for l in layers if name_q in l.get("name", "").lower()), None)
        if not layer:
            avail = ", ".join(l.get("name","?") for l in layers)
            return f"[UA ERROR] Layer '{name_q}' not found. Available: {avail}"
        node_map = {n["id"]: n for n in nodes}
        lines = [f"[UA LAYER] {layer.get('name','?')} - {len(layer.get('nodeIds', []))} nodes"]
        for nid in layer.get("nodeIds", [])[:count]:
            n = node_map.get(nid, {})
            lines.append(f"  - {n.get('name', nid)}")
        return "\n".join(lines)

    elif action == "ua_tour":
        if not tour:
            return "[UA TOUR] No tour steps. Re-run /understand to generate one."
        lines = [f"[UA TOUR] {proj.get('name','?')} - {len(tour)} steps"]
        for step in sorted(tour, key=lambda s: s.get("order", 0)):
            lines.append(f"  {step.get('order','?')}. {step.get('title','?')}")
        return "\n".join(lines)

    else:
        return f"[UA ERROR] Unknown action: {action!r}\n  Valid: ua_info | ua_search | ua_node | ua_layer | ua_tour"
